os: linux
dist: bionic
services:
- docker
language: go
go:
- '1.13'
python:
- '3.6'
addons:
  apt:
    packages:
    - flawfinder
    - squashfs-tools
    - uuid-dev
    - libuuid1
    - libffi-dev
    - libssl-dev
    - libssl1.0.0
    - libarchive-dev
    - libgpgme11-dev
    - libseccomp-dev
    - python3-pip
  homebrew:
    packages:
    - squashfs
    update: true
sudo: required
before_install:
- sudo apt-get install python3-setuptools
- sudo apt-get install libfuse2
- 'export VERSION=3.5.2 && wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
  && tar -xzf singularity-${VERSION}.tar.gz && cd singularity

  '
- "./mconfig && make -C builddir && sudo make -C builddir install && cd ..\n"
install:
- sudo pip3 install -e .
- sudo pip3 install -U pytest
script:
- "./scripts/bootstrap.sh"
- docker-compose -f docker-compose.test.yml up -d
- docker-compose -f docker-compose.test.yml exec -T slurmctld coverage run --source=plantit_cli -m pytest /opt/plantit-cli -s
- docker-compose -f docker-compose.test.yml exec -T slurmctld coveralls
- docker-compose -f docker-compose.test.yml down
after_script:
- python3 -m pip install --user --upgrade setuptools wheel
- python3 -m pip install --user --upgrade twine
- sudo python3 setup.py sdist bdist_wheel
- sudo python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
