dist: trusty

services:
  - docker

language: python
python:
  - "3.6"

before_install:
  - docker pull mjstealey/irods-provider-postgres:4.2.3
  - docker run -d -p 127.0.0.1:1247:1247 mjstealey/irods-provider-postgres:4.2.3
  - sudo apt-get install libfuse2
  - sudo apt-get install libfuse2
  - sudo wget https://files.renci.org/pub/irods/releases/4.1.12/ubuntu14/irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo dpkg -i irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo rm irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo chmod +x wait-for-postgres.sh
  - ./wait-for-postgres.sh 127.0.0.1
  - sleep 2
  - printf '127.0.0.1\n1247\nrods\ntempZone\nrods\n' | iinit
  - iput tests/sample1.jpg
  - iput tests/sample2.jpg
  - iput tests/sample3.jpg
  - >
    sudo apt-get update && sudo apt-get install -y
    build-essential
    libssl-dev
    uuid-dev
    libgpgme11-dev
    squashfs-tools
    libseccomp-dev
    wget
    pkg-config
    git
    cryptsetup
  - >
    export VERSION=1.14.2 OS=linux ARCH=amd64 &&
    wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz &&
    sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz &&
    rm go$VERSION.$OS-$ARCH.tar.gz
  - >
    echo 'export PATH=/usr/local/go/bin:$PATH' >> $HOME/.profile &&
    source $HOME/.profile
  - >
    export VERSION=3.5.2 &&
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz &&
    tar -xzf singularity-${VERSION}.tar.gz &&
    cd singularity
  - >
    ./mconfig &&
    make -C builddir &&
    sudo make -C builddir install

install:
  - pip3 install -e .
  - pip3 install pytest

script:
  - python3 -m pytest
  - python3 tests/test.py
