os: linux
dist: bionic

services:
  - docker

language: go

go:
  - "1.13"

python:
  - "3.6"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
      - python3-pip
  homebrew:
    packages:
      - squashfs
    update: true

sudo: required

before_install:
  - sudo apt-get install python3-setuptools
  - sudo apt-get install libfuse2
  - sudo wget https://files.renci.org/pub/irods/releases/4.1.12/ubuntu14/irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo dpkg -i irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo rm irods-icommands-4.1.12-ubuntu14-x86_64.deb
  - sudo chmod +x wait-for-postgres.sh
  - sudo chmod +x wait-for-it.sh
  - sudo chmod +x configure-irods.sh
  - >
    export VERSION=3.5.2 &&
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz &&
    tar -xzf singularity-${VERSION}.tar.gz &&
    cd singularity
  - >
    ./mconfig &&
    make -C builddir &&
    sudo make -C builddir install &&
    cd ..

install:
  - singularity pull docker://python:3.6-stretch
  - sudo pip3 install -e .
  - sudo pip3 install -U pytest

script:
  - python3 -m pytest
  - docker-compose -f docker-compose.test.yml up -d --build
  - ./wait-for-postgres.sh localhost
  - ./wait-for-it.sh localhost:1247 --
  - sleep 5
  - ./configure-irods.sh
  - iput tests/sample1.jpg
  - iput tests/sample2.jpg
  - iput tests/sample3.jpg
  - python3 tests/test.py
  - docker-compose -f docker-compose.test.yml down
