jobqueue:
  slurm:
    name: dask-worker
    cores: 1
    memory: 2GB
    processes: 1
    interface: null
    death-timeout: 60
    local-directory: null
    extra: []
    shebang: "#!/usr/bin/env bash"
    queue: normal
    project: plantit-cli
    walltime: '00:10:00'
    env-extra: []
    job-cpu: null
    job-mem: null
    job-extra: []
    log-directory: null
    scheduler-options: {}
  local:
    name: dask-worker
    cores: 1
    memory: 2GB
    processes: 1
    interface: null
    death-timeout: 60
    local-directory: null
    extra: []
    env-extra: []
    job-extra: []
    log-directory: null
    scheduler-options: {}
